version: "3.8"

services:
  web:
    image: heroku/herokuish:latest
    container_name: my_web
    build:
      context: .
      dockerfile: Dockerfile  # Menentukan Dockerfile jika Anda ingin kustomisasi lebih lanjut
    command: ["nixpacks", "build"]  # Memanggil Nixpacks untuk membangun aplikasi Anda
    ports:
      - "80:80"
    volumes:
      - .:/app  # Mount direktori lokal ke dalam container
    depends_on:
      - db
    restart: always
    environment:
      - APP_ENV=production
    networks:
      - app_network

  db:
    image: mariadb:latest
    container_name: my_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my_phpmyadmin
    restart: always
    ports:
      - "${PMA_PORT:-8080}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - app_network

volumes:
  db_data:
    driver: local

networks:
  app_network:
    driver: bridge
