FROM php:8.1-fpm-alpine

# Instal ekstensi yang diperlukan
RUN docker-php-ext-install pdo_mysql

# Beri hak akses ke direktori aplikasi
WORKDIR /var/www/html
COPY . /var/www/html
RUN chown -R www-data:www-data /var/www/html

# Expose port PHP-FPM
EXPOSE 9000

CMD ["php-fpm"]
